name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release zip
        run: |
          zip -r haven.zip . \
            --exclude "*.git*" \
            --exclude ".github/*"

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: haven.zip
